# Generated by Django 3.2.15 on 2024-12-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_business_products'),
        ('products', '0029_remove_product_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_packaged', models.BooleanField(default=False)),
                ('packing_data_time', models.DateTimeField(blank=True, null=True)),
                ('is_shipped', models.BooleanField(default=False)),
                ('shipping_data_time', models.DateTimeField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='main.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('packing_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrderPackage',
                'ordering': ['-pk'],
                'permissions': (('get.affiliate_factor', 'مشاهده بسته سفارش'), ('create.affiliate_factor', 'تعریف بسته سفارش'), ('update.affiliate_factor', 'ویرایش بسته سفارش'), ('delete.affiliate_factor', 'حذف بسته سفارش'), ('getOwn.affiliate_factor', 'مشاهده بسته سفارش خود'), ('updateOwn.affiliate_factor', 'ویرایش بسته سفارش خود'), ('deleteOwn.affiliate_factor', 'حذف بسته سفارش خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrderPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packing.orderpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'OrderPackageItem',
                'ordering': ['-pk'],
                'permissions': (('get.order_package_item', 'مشاهده آیتم بسته سفارش'), ('create.order_package_item', 'تعریف آیتم بسته سفارش'), ('update.order_package_item', 'ویرایش آیتم بسته سفارش'), ('delete.order_package_item', 'حذف آیتم بسته سفارش'), ('getOwn.order_package_item', 'مشاهده آیتم بسته سفارش خود'), ('updateOwn.order_package_item', 'ویرایش آیتم بسته سفارش خود'), ('deleteOwn.order_package_item', 'حذف آیتم بسته سفارش خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
