# Generated by Django 3.2.15 on 2024-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackageitem',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
