# Generated by Django 3.2.15 on 2024-09-02 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_category_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20240831_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrancePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_time', models.TimeField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_packages', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_packages', to='main.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_packages', to='main.supplier')),
            ],
            options={
                'verbose_name': 'EntrancePackage',
                'ordering': ['-pk'],
                'permissions': (('get.entrance_packages', 'مشاهده پکیج ورودی'), ('create.entrance_packages', 'تعریف پکیج ورودی'), ('update.entrance_packages', 'ویرایش پکیج ورودی'), ('delete.entrance_packages', 'حذف پکیج ورودی'), ('getOwn.entrance_packages', 'مشاهده پکیج ورودی خود'), ('updateOwn.entrance_packages', 'ویرایش پکیج ورودی خود'), ('deleteOwn.entrance_packages', 'حذف پکیج ورودی خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StoreReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enter_date', models.DateField(blank=True, null=True)),
                ('enter_time', models.TimeField(blank=True, null=True)),
                ('box_count', models.IntegerField(default=0)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entrance_packages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_receipt', to='entrance.entrancepackage')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_receipt', to='main.store')),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_receipt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StoreReceipt',
                'ordering': ['-pk'],
                'permissions': (('get.store_receipt', 'مشاهده رسید ورود انبار'), ('create.store_receipt', 'تعریف رسید ورود انبار'), ('update.store_receipt', 'ویرایش رسید ورود انبار'), ('delete.store_receipt', 'حذف رسید ورود انبار'), ('getOwn.store_receipt', 'مشاهده رسید ورود انبار خود'), ('updateOwn.store_receipt', 'ویرایش رسید ورود انبار خود'), ('deleteOwn.store_receipt', 'حذف رسید ورود انبار خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StoreReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('b', 'کارتون'), ('w', 'فله')], default='b', max_length=1)),
                ('product_in_box_count', models.IntegerField(default=0)),
                ('box_count', models.IntegerField(default=0)),
                ('product_code', models.CharField(blank=True, max_length=150, null=True)),
                ('margin_profit_percent', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('default_picture', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('content_production_count', models.IntegerField(default=0)),
                ('postal_weight', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('product_date', models.DateField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('new_product_shelf_code', models.IntegerField(blank=True, null=True)),
                ('default_name', models.CharField(max_length=150)),
                ('default_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_receipt_items', to='main.currency')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_receipt_items', to='products.product')),
                ('store_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='entrance.storereceipt')),
            ],
            options={
                'verbose_name': 'StoreReceiptItem',
                'ordering': ['-pk'],
                'permissions': (('get.store_receipt', 'مشاهده ردیف رسید ورود انبار'), ('create.store_receipt', 'تعریف ردیف رسید ورود انبار'), ('update.store_receipt', 'ویرایش ردیف رسید ورود انبار'), ('delete.store_receipt', 'حذف ردیف رسید ورود انبار'), ('getOwn.store_receipt', 'مشاهده ردیف رسید ورود انبار خود'), ('updateOwn.store_receipt', 'ویرایش ردیف رسید ورود انبار خود'), ('deleteOwn.store_receipt', 'حذف ردیف رسید ورود انبار خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EntrancePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('product_code', models.CharField(blank=True, max_length=150, null=True)),
                ('default_picture', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('default_name', models.CharField(max_length=150)),
                ('product_in_box_count', models.IntegerField(default=0)),
                ('box_count', models.IntegerField(default=0)),
                ('default_price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('margin_profit_percent', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('content_production_count', models.IntegerField(default=0)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_package_items', to='main.currency')),
                ('entrance_packages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='entrance.entrancepackage')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_package_items', to='products.product')),
            ],
            options={
                'verbose_name': 'EntrancePackageItem',
                'ordering': ['-pk'],
                'permissions': (('get.entrance_package_item', 'مشاهده ردیف پکیج ورودی'), ('create.entrance_package_item', 'تعریف ردیف پکیج ورودی'), ('update.entrance_package_item', 'ویرایش  ردیفپکیج ورودی'), ('delete.entrance_package_item', 'حذف ردیف پکیج ورودی'), ('getOwn.entrance_packages', 'مشاهده ردیف پکیج ورودی خود'), ('updateOwn.entrance_packages', 'ویرایش ردیف پکیج ورودی خود'), ('deleteOwn.entrance_packages', 'حذف ردیف پکیج ورودی خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
