# Generated by Django 3.2.15 on 2024-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereceipt',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
