# Generated by Django 3.2.15 on 2024-09-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_storereceipt_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrancepackage',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.entrance_package', 'مشاهده پکیج ورودی'), ('create.entrance_package', 'تعریف پکیج ورودی'), ('update.entrance_package', 'ویرایش پکیج ورودی'), ('delete.entrance_package', 'حذف پکیج ورودی'), ('getOwn.entrance_package', 'مشاهده پکیج ورودی خود'), ('updateOwn.entrance_package', 'ویرایش پکیج ورودی خود'), ('deleteOwn.entrance_package', 'حذف پکیج ورودی خود')), 'verbose_name': 'EntrancePackage'},
        ),
    ]
