# Generated by Django 3.2.15 on 2024-10-14 12:20

from django.db import migrations, models
import entrance.models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0003_alter_entrancepackage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackage',
            name='entrance_file',
            field=models.FileField(blank=True, null=True, upload_to=entrance.models.excel_upload_to),
        ),
    ]
