# Generated by Django 3.2.15 on 2024-10-14 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrance', '0004_entrancepackage_entrance_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrancePackageFileColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('key', models.CharField(choices=[('p', 'مبلغ محصول'), ('n', 'نام محصول'), ('c', 'کد محصول'), ('q', 'تعداد محصول'), ('b', 'تعداد کارتون محصول')], max_length=1)),
                ('column_number', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entrance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_columns', to='entrance.entrancepackage')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
