# Generated by Django 3.2.15 on 2024-10-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240906_1455'),
        ('entrance', '0005_entrancepackagefilecolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackage',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrance_packages', to='main.currency'),
        ),
        migrations.AddField(
            model_name='entrancepackagefilecolumn',
            name='in_case_of_sale_type',
            field=models.CharField(blank=True, choices=[('m', 'دستی'), ('a', 'مبلغ'), ('p', 'درصد')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='entrancepackagefilecolumn',
            name='key',
            field=models.CharField(choices=[('pp', 'مبلغ محصول'), ('pn', 'نام محصول'), ('pc', 'کد محصول'), ('nb', 'تعداد کارتون'), ('pb', 'تعداد محصول در کارتون'), ('sd', 'کد 16 رقمی'), ('ic', 'قیمت در صورت فروش'), ('ba', 'بارکد'), ('im', 'تصویر')], max_length=2),
        ),
    ]
