# Generated by Django 3.2.15 on 2024-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0006_auto_20241015_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackage',
            name='is_inserted',
            field=models.BooleanField(default=False),
        ),
    ]
