# Generated by Django 3.2.15 on 2024-10-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_entrancepackage_is_inserted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrancepackageitem',
            old_name='box_count',
            new_name='number_of_box',
        ),
    ]
