# Generated by Django 3.2.15 on 2024-10-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0008_rename_box_count_entrancepackageitem_number_of_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrancepackageitem',
            old_name='product_in_box_count',
            new_name='number_of_products_per_box',
        ),
        migrations.AddField(
            model_name='entrancepackageitem',
            name='in_case_of_sale_type',
            field=models.CharField(blank=True, choices=[('m', 'دستی'), ('a', 'مبلغ'), ('p', 'درصد')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='entrancepackageitem',
            name='price_in_case_of_sale',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='entrancepackageitem',
            name='sixteen_digit_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
