# Generated by Django 3.2.15 on 2024-10-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0009_auto_20241015_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackageitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
