# Generated by Django 3.2.15 on 2024-10-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0010_entrancepackageitem_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrancepackageitem',
            old_name='entrance_packages',
            new_name='entrance_package',
        ),
    ]
