# Generated by Django 3.2.15 on 2024-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0011_rename_entrance_packages_entrancepackageitem_entrance_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackageitem',
            name='price_sum',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='entrancepackagefilecolumn',
            name='key',
            field=models.CharField(choices=[('pp', 'مبلغ محصول'), ('pn', 'نام محصول'), ('pc', 'کد محصول'), ('nb', 'تعداد کارتون'), ('pb', 'تعداد محصول در کارتون'), ('sd', 'کد 16 رقمی'), ('ic', 'قیمت در صورت فروش'), ('ba', 'بارکد'), ('im', 'تصویر'), ('ps', 'مبلغ کل')], max_length=2),
        ),
    ]
