# Generated by Django 3.2.15 on 2024-10-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0012_auto_20241022_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackageitem',
            name='number_of_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrancepackagefilecolumn',
            name='key',
            field=models.CharField(choices=[('pp', 'مبلغ محصول'), ('pn', 'نام محصول'), ('pc', 'کد محصول'), ('nb', 'تعداد کارتون'), ('pb', 'تعداد محصول در کارتون'), ('np', 'تعداد محصول'), ('sd', 'کد 16 رقمی'), ('ic', 'قیمت در صورت فروش'), ('ba', 'بارکد'), ('im', 'تصویر'), ('ps', 'مبلغ کل')], max_length=2),
        ),
    ]
