# Generated by Django 3.2.15 on 2024-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0013_auto_20241026_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancepackagefilecolumn',
            name='in_case_of_sale_type',
            field=models.CharField(blank=True, choices=[('a', 'مبلغ'), ('p', 'درصد')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='entrancepackageitem',
            name='in_case_of_sale_type',
            field=models.CharField(choices=[('a', 'مبلغ'), ('p', 'درصد')], default='a', max_length=2),
        ),
    ]
