# Generated by Django 3.2.15 on 2024-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0014_auto_20241026_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackageitem',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='entrancepackageitem',
            name='discount_type',
            field=models.CharField(choices=[('a', 'مبلغ'), ('p', 'درصد')], default='a', max_length=2),
        ),
    ]
