# Generated by Django 3.2.15 on 2024-10-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0015_auto_20241026_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancepackageitem',
            name='number_of_box',
            field=models.IntegerField(default=1),
        ),
    ]
