# Generated by Django 3.2.15 on 2024-10-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0016_alter_entrancepackageitem_number_of_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storereceiptitem',
            old_name='box_count',
            new_name='number_of_products_per_box',
        ),
        migrations.RemoveField(
            model_name='storereceiptitem',
            name='product_in_box_count',
        ),
        migrations.AddField(
            model_name='storereceiptitem',
            name='number_of_box',
            field=models.IntegerField(default=1),
        ),
    ]
