# Generated by Django 3.2.15 on 2024-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0017_auto_20241027_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackageitem',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
