# Generated by Django 3.2.15 on 2024-10-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0018_entrancepackageitem_failure_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereceiptitem',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
