# Generated by Django 3.2.15 on 2024-11-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0019_storereceiptitem_failure_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackage',
            name='factor_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
