# Generated by Django 3.2.15 on 2024-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0020_entrancepackage_factor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereceiptitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
