# Generated by Django 3.2.15 on 2024-11-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0021_storereceiptitem_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancepackageitem',
            name='entrance_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entrance.entrancepackage'),
        ),
        migrations.AlterField(
            model_name='storereceiptitem',
            name='store_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entrance.storereceipt'),
        ),
    ]
