# Generated by Django 3.2.15 on 2024-11-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240906_1455'),
        ('entrance', '0022_auto_20241101_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereceipt',
            name='entrance_packages',
        ),
        migrations.AddField(
            model_name='storereceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_receipt', to='main.supplier'),
        ),
    ]
