# Generated by Django 3.2.15 on 2024-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0023_auto_20241103_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrancepackageitem',
            name='number_of_products',
        ),
        migrations.AddField(
            model_name='entrancepackage',
            name='with_offer',
            field=models.BooleanField(default=False),
        ),
    ]
