# Generated by Django 3.2.15 on 2024-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0024_auto_20241105_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancepackageitem',
            name='initial_registration',
            field=models.BooleanField(default=False),
        ),
    ]
