# Generated by Django 3.2.15 on 2024-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0026_alter_entrancepackagefilecolumn_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereceiptitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
