# Generated by Django 3.2.15 on 2024-12-21 12:53

from django.db import migrations, models
import entrance.models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0027_storereceiptitem_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancepackageitem',
            name='default_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=entrance.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='storereceiptitem',
            name='default_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=entrance.models.custom_upload_to),
        ),
    ]
