# Generated by Django 3.2.15 on 2025-08-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20250720_1527'),
        ('entrance', '0028_auto_20241221_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaEntrancePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('factor_number', models.CharField(blank=True, max_length=150, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('cargo_cost_per_shipping', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extracted_entrance_packages', to='main.currency')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_entrance_packages', to='main.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ChinaEntrancePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('box_stacking', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_per_box', models.PositiveIntegerField(blank=True, null=True)),
                ('box_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entrance.chinaentrancepackage')),
            ],
        ),
    ]
