# Generated by Django 3.2.15 on 2025-08-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0015_alter_extractedentrancepackage_name'),
        ('entrance', '0029_chinaentrancepackage_chinaentrancepackageitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinaentrancepackage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chinaentrancepackage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='chinaentrancepackage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chinaentrancepackage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='chinaentrancepackage',
            name='xlsx_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='china_entrance_package', to='file_handler.extractedentrancepackage'),
        ),
    ]
