# Generated by Django 3.2.15 on 2025-08-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0030_auto_20250825_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaentrancepackageitem',
            name='box_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chinaentrancepackageitem',
            name='quantity_per_box',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
