# Generated by Django 3.2.15 on 2025-08-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0031_auto_20250825_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaEntrancePackageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('driver_name', models.CharField(blank=True, max_length=150, null=True)),
                ('driver_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, help_text='شماره رسید یا مدرک تحویل (اختیاری)', max_length=150, null=True)),
                ('total_boxes', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='entrance.chinaentrancepackage')),
            ],
        ),
        migrations.CreateModel(
            name='ChinaEntrancePackageDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes_delivered', models.PositiveIntegerField(default=1)),
                ('quantity_per_box', models.PositiveIntegerField(default=1)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entrance.chinaentrancepackagedelivery')),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='entrance.chinaentrancepackageitem')),
            ],
        ),
    ]
