# Generated by Django 3.2.15 on 2025-08-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_auto_20250819_2206'),
        ('entrance', '0033_chinaentrancepackageitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinaentrancepackageitem',
            name='product',
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedelivery',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivers', to='products.product'),
        ),
    ]
