# Generated by Django 3.2.15 on 2025-08-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0034_auto_20250826_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaentrancepackageitem',
            name='final_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackageitem',
            name='profit_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackageitem',
            name='profit_type',
            field=models.CharField(choices=[('percent', ' درصدی'), ('amount', ' مبلغی')], default='percent', max_length=10),
        ),
    ]
