# Generated by Django 3.2.15 on 2025-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0035_auto_20250827_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='aisle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='crashed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='expired_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='inserted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='min_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='postal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='shelf_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
