# Generated by Django 3.2.15 on 2025-08-27 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20250720_1527'),
        ('entrance', '0036_auto_20250827_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaentrancepackagedeliveryitem',
            name='to_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='main.store'),
        ),
    ]
