# Generated by Django 3.2.15 on 2024-08-16 12:39

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری باید از حدوف و اعداد انگلیسی تشکیل شود', regex='^[a-zA-Z0-9]+$')])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=11)),
                ('modules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('max_companies', models.IntegerField(default=0)),
                ('max_users', models.IntegerField(default=0)),
                ('secret_key', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('profile_picture', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'auth_user',
                'permissions': (('get.user', 'مشاهده کاربر'), ('create.user', 'تعریف کاربر'), ('update.user', 'ویرایش کاربر'), ('delete.user', 'حذف کاربر'), ('changePassword.user', 'تغییر کلمه عبور کاربران'), ('getOwn.user', 'مشاهده کاربران خود'), ('updateOwn.user', 'ویرایش کاربران خود'), ('deleteOwn.user', 'حذف کاربران خود'), ('changePasswordOwn.user', 'تغییر کلمه عبور کاربران خود')),
                'abstract': False,
                'default_permissions': (),
            },
            managers=[
                ('objects', users.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('su', 'ارسال شده توسط کاربر'), ('sr', 'یاداور'), ('ss', 'ارسال شده توسط سامانه'), ('sa', 'ارسال شده توسط ادمین')], max_length=2)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('show_pop_up', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('has_schedule', models.BooleanField(default=False)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('send_time', models.TimeField(blank=True, null=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('notification_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_explanation', models.TextField(blank=True, null=True)),
                ('notification_link', models.CharField(blank=True, max_length=255, null=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('sms_text', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receivers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('send.notification', 'ارسال اعلان به سایر کاربران شرکت'),),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2)),
                ('notification_status', models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True)),
                ('sms_status', models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userNotifications', to='users.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='auth.Permission')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.role', 'مشاهده نقش'), ('create.role', 'تعریف نقش'), ('update.role', 'ویرایش نقش'), ('delete.role', 'حذف نقش'), ('getOwn.role', 'مشاهده نقش خود'), ('updateOwn.role', 'ویرایش نقش خود'), ('deleteOwn.role', 'حذف نقش خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('code', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=11)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificationCodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'id',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('create.city', 'تعریف شهر'), ('get.city', 'مشاهده شهر'), ('update.city', 'ویرایش شهر'), ('delete.city', 'حذف شهر'), ('getOwn.city', 'مشاهده شهر های خود'), ('updateOwn.city', 'ویرایش شهر های خود'), ('deleteOwn.city', 'حذف شهر های خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='superuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
