# Generated by Django 3.2.15 on 2024-08-30 13:03

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_companies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='about_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, choices=[('BCDEVE', 'بانک توسعه تعاون'), ('BCITY', 'بانک شهر'), ('BDAY', 'بانک دی'), ('BEDIRA', 'بانک توسعه صادرات  ایران'), ('BEGHTE', 'بانک اقتصاد نوین'), ('BGHARZ', 'بانک قرض الحسنه مهر ایران'), ('BINDMI', 'بانک صنعت و معدن'), ('BKARAF', 'بانک کارآفرین'), ('BKESHA', 'بانک کشاورزی'), ('BMASKA', 'بانک مسکن'), ('BMELLA', 'بانک ملت'), ('BMELLI', 'بانک  ملی ایران'), ('BPARSI', 'بانک پارسیان'), ('BPASAR', 'بانک پاسارگاد'), ('BPOST', 'پست بانک'), ('BREFAH', 'بانک  رفاه کارگران'), ('BSADER', 'بانک صادرات'), ('BSAMAN', 'بانک سامان'), ('BSARMA', 'بانک سرمایه'), ('BSEPAH', 'بانک  سپه'), ('BSINA', 'بانک سینا'), ('BTEJAR', 'بانک تجارت'), ('BTOURI', 'بانک  گردشگری'), ('BRESALA', 'بانک قرض الحسنه رسالت'), ('BAYAN', 'بانک آینده'), ('CHART', 'استاندارد چارترد'), ('EURO', 'بانک تجاری ایران و اروپا'), ('KHAVA', 'بانک خاورمیانه'), ('VENE', 'بانک مشترک ایران - ونزوئلا'), ('ESLA', 'تعاون اسلامی برای سرمایه\u200cگذاری'), ('FUTU', 'فیوچر بانک (المستقبل)'), ('CASP', 'مؤسسه اعتباری غیربانکی کاسپین '), ('TOSE', 'مؤسسه اعتباری غیربانکی توسعه '), ('MELAL', 'مؤسسه اعتباری غیربانکی ملل '), ('NOR', 'مؤسسه اعتباری غیربانکی نور '), ('ZAMIN', 'بانک ایران زمین')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_sheba_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ma', 'مدیر'), ('stke', 'انباردار'), ('copr', 'ادمین  تولید محتوا'), ('saad', 'ادمین  فروش دستی'), ('cu', 'مشتری'), ('paad', 'ادمین بسته بندی'), ('buow', 'صاحب کسب و کار'), ('prdead', 'ادمین خروج کالا'), ('suad', 'ادمین تامین کننده')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'این نام کاربری قبلا در اکسونی ثبت شده'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری باید از حدوف و اعداد انگلیسی تشکیل شود', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
