# Generated by Django 3.2.15 on 2024-08-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240830_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ma', 'مدیر'), ('stke', 'انباردار'), ('copr', 'ادمین  تولید محتوا'), ('saad', 'ادمین  فروش دستی'), ('cu', 'مشتری'), ('paad', 'ادمین بسته بندی'), ('buow', 'صاحب کسب و کار'), ('prdead', 'ادمین خروج کالا'), ('suad', 'ادمین تامین کننده')], default='cu', max_length=6),
        ),
    ]
