# Generated by Django 3.2.15 on 2024-08-30 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'این نام کاربری از قبل در اکسونی ثبت شده'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری باید از حدوف و اعداد انگلیسی تشکیل شود', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
