# Generated by Django 3.2.15 on 2024-11-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('users', '0006_auto_20241118_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.wallet'),
        ),
    ]
