# Generated by Django 3.2.15 on 2025-06-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user__wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'این نام از قبل در اکسونی ثبت شده'}, max_length=150, unique=True),
        ),
    ]
