# Generated by Django 3.2.15 on 2025-08-26 15:29

from django.db import migrations, models


def create_admin_access(apps, schema_editor):
    AdminAccess = apps.get_model("users", "AdminAccess")
    code_types = [
        ("pack", "بسته بندی"),
        ("prent", "ورود کالا"),
        ("skued", "ویرایش SKU"),
        ("prined", "ویرایش اطلاعات کالا"),
        ("trans", "انتقال"),
    ]
    for code, _ in code_types:
        AdminAccess.objects.get_or_create(code=code)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('pack', 'بسته بندی'), ('prent', 'ورود کالا'), ('skued', 'ویرایش SKU'), ('prined', 'ویرایش اطلاعات کالا'), ('trans', 'انتقال')], default='pack', max_length=6, unique=True)),
            ],
        ),
        migrations.RunPython(create_admin_access),

    ]
