# Generated by Django 3.2.15 on 2025-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_adminaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accesses',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.AdminAccess'),
        ),
    ]
