# Generated by Django 3.2.15 on 2024-11-18 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20240906_1455'),
        ('products', '0009_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_factors', to='main.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_factors_as_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AffiliateFactor',
                'ordering': ['-pk'],
                'permissions': (('get.affiliate_factor', 'مشاهده فاکتور افیلیت'), ('create.affiliate_factor', 'تعریف فاکتور افیلیت'), ('update.affiliate_factor', 'ویرایش فاکتور افیلیت'), ('delete.affiliate_factor', 'حذف فاکتور افیلیت'), ('getOwn.affiliate_factor', 'مشاهده فاکتور افیلیت خود'), ('updateOwn.affiliate_factor', 'ویرایش فاکتور افیلیت خود'), ('deleteOwn.affiliate_factor', 'حذف فاکتور افیلیت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AffiliateFactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('affiliate_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='affiliate.affiliatefactor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_factor_items', to='products.product')),
            ],
            options={
                'verbose_name': 'AffiliateFactorItem',
                'ordering': ['-pk'],
                'permissions': (('get.affiliate_factor_item', 'مشاهده ردیف فاکتور افیلیت'), ('create.affiliate_factor_item', 'تعریف ردیف فاکتور افیلیت'), ('update.affiliate_factor_item', 'ویرایش ردیف فاکتور افیلیت'), ('delete.affiliate_factor_item', 'حذف ردیف فاکتور افیلیت'), ('getOwn.affiliate_factor', 'مشاهده ردیف فاکتور افیلیت خود'), ('updateOwn.affiliate_factor', 'ویرایش ردیف فاکتور افیلیت خود'), ('deleteOwn.affiliate_factor', 'حذف ردیف فاکتور افیلیت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
