# Generated by Django 3.2.15 on 2024-11-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatefactor',
            name='status',
            field=models.CharField(choices=[('irs', 'ثبت اولیه'), ('ipr', 'درحال پردازش'), ('ipa', 'در حال بسته بندی'), ('shp', 'ارسال شده')], default='irs', max_length=3),
        ),
    ]
