# Generated by Django 3.2.15 on 2024-11-20 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_business_api_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliate', '0002_affiliatefactor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('payment_data_time', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_invoices', to='main.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PaymentInvoice',
                'ordering': ['-pk'],
                'permissions': (('get.payment_invoice', 'مشاهده فاکتور پرداخت'), ('create.payment_invoice', 'تعریف فاکتور پرداخت'), ('update.payment_invoice', 'ویرایش فاکتور پرداخت'), ('delete.payment_invoice', 'حذف فاکتور پرداخت'), ('getOwn.payment_invoice', 'مشاهده فاکتور پرداخت خود'), ('updateOwn.payment_invoice', 'ویرایش فاکتور پرداخت خود'), ('deleteOwn.payment_invoice', 'حذف فاکتور پرداخت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='affiliatefactoritem',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.affiliate_factor_item', 'مشاهده ردیف فاکتور افیلیت'), ('create.affiliate_factor_item', 'تعریف ردیف فاکتور افیلیت'), ('update.affiliate_factor_item', 'ویرایش ردیف فاکتور افیلیت'), ('delete.affiliate_factor_item', 'حذف ردیف فاکتور افیلیت'), ('getOwn.affiliate_factor_item', 'مشاهده ردیف فاکتور افیلیت خود'), ('updateOwn.affiliate_factor_item', 'ویرایش ردیف فاکتور افیلیت خود'), ('deleteOwn.affiliate_factor_item', 'حذف ردیف فاکتور افیلیت خود')), 'verbose_name': 'AffiliateFactorItem'},
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('balance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='main.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('d', 'واریز'), ('w', 'برداشت'), ('p', 'پرداخت')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('bed', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('bes', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('datetime', models.DateTimeField()),
                ('_is_successful', models.BooleanField(default=False)),
                ('_order_id', models.BigIntegerField(blank=True, null=True)),
                ('_gateway_callback', models.JSONField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='affiliate.paymentinvoice')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='affiliate.wallet')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('caf', 'فاکتور مشتری افیلیت')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='affiliate.paymentinvoice')),
            ],
            options={
                'verbose_name': 'AffiliateFactorItem',
                'ordering': ['-pk'],
                'permissions': (('get.payment_invoice_item', 'مشاهده ردیف فاکتور پرداخت '), ('create.payment_invoice_item', 'تعریف ردیف فاکتور پرداخت'), ('update.payment_invoice_item', 'ویرایش ردیف فاکتور پرداخت'), ('delete.payment_invoice_item', 'حذف ردیف فاکتور پرداخت'), ('getOwn.payment_invoice_item', 'مشاهده ردیف فاکتور پرداخت خود'), ('updateOwn.payment_invoice_item', 'ویرایش ردیف فاکتور پرداخت خود'), ('deleteOwn.payment_invoice_item', 'حذف ردیف فاکتور پرداخت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
