# Generated by Django 3.2.15 on 2024-11-20 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_auto_20241120_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoiceitem',
            name='affiliate_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_invoice', to='affiliate.affiliatefactor'),
        ),
    ]
