# Generated by Django 3.2.15 on 2024-11-20 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_paymentinvoiceitem_affiliate_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinvoiceitem',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.payment_invoice_item', 'مشاهده ردیف فاکتور پرداخت '), ('create.payment_invoice_item', 'تعریف ردیف فاکتور پرداخت'), ('update.payment_invoice_item', 'ویرایش ردیف فاکتور پرداخت'), ('delete.payment_invoice_item', 'حذف ردیف فاکتور پرداخت'), ('getOwn.payment_invoice_item', 'مشاهده ردیف فاکتور پرداخت خود'), ('updateOwn.payment_invoice_item', 'ویرایش ردیف فاکتور پرداخت خود'), ('deleteOwn.payment_invoice_item', 'حذف ردیف فاکتور پرداخت خود')), 'verbose_name': 'PaymentInvoiceItem'},
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_data_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 23, 24, 18, 301346)),
        ),
    ]
