# Generated by Django 3.2.15 on 2024-11-21 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_auto_20241120_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='business',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_data_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 20, 14, 1, 180624)),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
