# Generated by Django 3.2.15 on 2024-11-21 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_auto_20241121_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_data_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 20, 15, 24, 540139)),
        ),
    ]
