# Generated by Django 3.2.15 on 2024-11-22 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0007_alter_paymentinvoice_payment_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_data_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 16, 2, 26, 629371)),
        ),
    ]
