# Generated by Django 3.2.15 on 2024-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0009_alter_paymentinvoice_payment_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='payment_data_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
