# Generated by Django 3.2.15 on 2024-11-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0010_alter_paymentinvoice_payment_data_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinvoiceitem',
            name='affiliate_factor',
        ),
        migrations.RemoveField(
            model_name='paymentinvoiceitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentinvoiceitem',
            name='payment_invoice',
        ),
        migrations.DeleteModel(
            name='PaymentInvoice',
        ),
        migrations.DeleteModel(
            name='PaymentInvoiceItem',
        ),
    ]
