# Generated by Django 3.2.15 on 2024-11-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0011_auto_20241122_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatefactor',
            name='status',
            field=models.CharField(choices=[('irs', 'ثبت اولیه'), ('pid', 'پرداخت شده')], default='irs', max_length=3),
        ),
    ]
