# Generated by Django 3.2.15 on 2025-07-18 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import issues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=issues.models.custom_upload_to)),
                ('issue_type', models.CharField(choices=[('bug', 'باگ'), ('feature', 'قابلیت جدید')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'درح حال انجام'), ('done', 'انجام شد')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_tested', models.BooleanField(default=False)),
                ('severity', models.IntegerField(choices=[(1, 'اولویت کم'), (2, 'اولویت متوسط'), (3, 'اولویت زیاد')], default=2)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'درح حال انجام'), ('done', 'انجام شد')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'جدید'), ('in_progress', 'درح حال انجام'), ('done', 'انجام شد')], max_length=20)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='issues.issue')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
