# Generated by Django 3.2.15 on 2025-08-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0033_auto_20250805_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('entrance_packages', ' پکیج ورودی'), ('post_report', ' گزارش پست')], max_length=55)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedPostReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_tracking_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('extracted_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='file_handler.extractedpostreport')),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_report_items', to='shop.shoporder')),
            ],
        ),
        migrations.AddField(
            model_name='extractedpostreport',
            name='uploaded_file',
            field=models.OneToOneField(limit_choices_to={'type': 'post_report'}, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_post_report', to='file_handler.uploadedfile'),
        ),
    ]
