# Generated by Django 3.2.15 on 2025-08-10 20:52

from django.db import migrations, models
import file_handler.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedpostreport',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=file_handler.models.custom_upload_to),
        ),
    ]
