# Generated by Django 3.2.15 on 2025-08-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20250805_2153'),
        ('file_handler', '0002_auto_20250810_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedpostreportitem',
            name='type',
            field=models.CharField(choices=[('f', ' سفارش'), ('n', ' نا معلوم')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='extractedpostreportitem',
            name='shop_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_report_items', to='shop.shoporder'),
        ),
    ]
