# Generated by Django 3.2.15 on 2025-08-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0003_auto_20250811_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractedpostreportitem',
            old_name='type',
            new_name='status',
        ),
    ]
