# Generated by Django 3.2.15 on 2025-08-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0004_rename_type_extractedpostreportitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedpostreport',
            name='uploaded_file',
            field=models.OneToOneField(limit_choices_to={'file_type': 'post_report'}, on_delete=django.db.models.deletion.CASCADE, related_name='extracted_post_report', to='file_handler.uploadedfile'),
        ),
    ]
