# Generated by Django 3.2.15 on 2025-08-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0005_alter_extractedpostreport_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedpostreportitem',
            name='explanation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
