# Generated by Django 3.2.15 on 2025-08-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0007_extractedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedEntrancePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.OneToOneField(limit_choices_to={'file_type': 'entrance_packages'}, on_delete=django.db.models.deletion.CASCADE, related_name='entrance_packages', to='file_handler.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedEntrancePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', 'قیمت اولیه'), ('g', 'کد محصول'), ('n', 'نام اولیه'), ('b', 'چیدمان جعبه'), ('qpb', 'تعداد در هر جعبه'), ('tq', 'تعداد کل'), ('ta', 'مبلغ کل'), ('u', 'نامشخص')], default='u', max_length=5)),
                ('price', models.FloatField(blank=True, null=True)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('box_stacking', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_per_box', models.PositiveIntegerField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='file_handler.extractedentrancepackage')),
            ],
        ),
    ]
