# Generated by Django 3.2.15 on 2025-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0008_extractedentrancepackage_extractedentrancepackageitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentrancepackageitem',
            name='box_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedentrancepackageitem',
            name='type',
            field=models.CharField(choices=[('p', 'قیمت اولیه'), ('g', 'کد محصول'), ('n', 'نام اولیه'), ('b', 'چیدمان جعبه'), ('qpb', 'تعداد در هر جعبه'), ('tq', 'تعداد کل'), ('bq', 'تعداد جعبه'), ('ta', 'مبلغ کل'), ('u', 'نامشخص')], default='u', max_length=5),
        ),
    ]
