# Generated by Django 3.2.15 on 2025-08-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0009_auto_20250825_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentrancepackageitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedentrancepackage',
            name='uploaded_file',
            field=models.OneToOneField(limit_choices_to={'file_type': 'entrance_packages'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_packages', to='file_handler.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='extractedentrancepackageitem',
            name='type',
            field=models.CharField(choices=[('p', 'قیمت اولیه'), ('g', 'کد محصول'), ('n', 'نام اولیه'), ('b', 'چیدمان جعبه'), ('qpb', 'تعداد در هر جعبه'), ('tq', 'تعداد کل'), ('bq', 'تعداد جعبه'), ('ta', 'مبلغ کل'), ('img', 'تصویر محصول'), ('u', 'نامشخص')], default='u', max_length=5),
        ),
    ]
