# Generated by Django 3.2.15 on 2025-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0010_auto_20250825_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedentrancepackageitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
