# Generated by Django 3.2.15 on 2025-08-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0011_alter_extractedentrancepackageitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedentrancepackageitem',
            name='type',
        ),
    ]
