# Generated by Django 3.2.15 on 2025-08-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20250720_1527'),
        ('file_handler', '0012_remove_extractedentrancepackageitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='cargo_cost_per_shipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extracted_entrance_packages', to='main.currency'),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='factor_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_entrance_packages', to='main.supplier'),
        ),
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='extractedentrancepackage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
