# Generated by Django 3.2.15 on 2025-08-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0013_auto_20250825_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='cargo_cost_per_shipping',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='factor_number',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='extractedentrancepackage',
            name='title',
        ),
        migrations.AlterField(
            model_name='extractedentrancepackage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
