# Generated by Django 3.2.15 on 2025-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0014_auto_20250825_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedentrancepackage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
