# Generated by Django 3.2.15 on 2025-08-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0015_alter_extractedentrancepackage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentrancepackage',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
