# Generated by Django 3.2.15 on 2025-08-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0016_extractedentrancepackage_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedentrancepackageitem',
            name='box_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extractedentrancepackageitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='extractedentrancepackageitem',
            name='quantity_per_box',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
