# Generated by Django 3.2.15 on 2024-11-21 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('code', models.CharField(max_length=31, unique=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('max_discount_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('usage', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(choices=[('EIGHT_LEVEL_ACCOUNTING', 'حسابداری 8 سطحی'), ('ONLINE_SUPPORT', 'پشتیبانی آنلاین'), ('PAYROLL', 'منابع انسانی'), ('MOADIAN', 'مودیان'), ('PROFESSIONAL_DASHBOARD', 'داشبورد حرفه ای'), ('WOOCOMMERCE_API', 'پلاگین فروشگاهی و API'), ('CREATE_NEW_ACCOUNT', 'تعریف حساب'), ('CREATE_NEW_CHEQUE', 'تعریف چک'), ('CREATE_NEW_IMPREST', 'تعریف تنخواه'), ('PROFESSIONAL_REPORT', 'گزارشات حرفه ای'), ('DAEMI_SYSTEM', 'سیستم دائمی'), ('FIRST_IN_FIRST_OUT_PRICING', 'قیمت گذاری کالا به روش فایفو'), ('UNLIMITED_CREATE_PERSON', 'تعریف نامحدود حساب اشخاص'), ('UNLIMITED_CREATE_TREASURY_ACCOUNT', 'تعریف نامحدود حساب های خزانه'), ('INVENTORY_CLERK', 'انبار گردانی'), ('CONSUMPTION_WARE_FACTOR', 'حواله کالای مصرفی'), ('RECEIPT_AND_REMITTANCE', 'رسید و حواله، تعدیل انبار'), ('GROUP_PRICE_CHANGE', 'تغییر گروهی قیمت کالا ')], max_length=100, unique=True)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('is_active', models.BooleanField(default=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.discountcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('balance', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('d', 'واریز'), ('w', 'برداشت')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('bed', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('bes', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('datetime', models.DateTimeField()),
                ('_is_successful', models.BooleanField(default=False)),
                ('_order_id', models.BigIntegerField(blank=True, null=True)),
                ('_gateway_callback', models.JSONField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.factor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.wallet')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(max_length=300)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('prices', models.JSONField(default=dict)),
                ('extra_user_prices', models.JSONField(default=dict)),
                ('users_count', models.IntegerField()),
                ('modules', models.CharField(blank=True, max_length=1000)),
                ('features', models.CharField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('addUser.plan', 'افزودن کاربر اشتراک'), ('extendSubscription.plan', 'تمدید اشتراک')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FactorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('cc', 'ساخت شرکت'), ('be', 'خرید ماژول'), ('ee', 'تمدید ماژول'), ('au', 'اضافه کردن کاربر'), ('aw', 'اضافه کردن انبار'), ('o', 'سایر')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('explanation', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_factor_items', to='subscription.extension')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscription.factor')),
            ],
            options={
                'ordering': ['pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompanyExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('expire_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_extensions', to='subscription.extension')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
