# Generated by Django 3.2.15 on 2024-11-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0008_alter_paymentinvoice_payment_data_time'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoritem',
            name='affiliate_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_factor_items', to='affiliate.affiliatefactor'),
        ),
    ]
