# Generated by Django 3.2.15 on 2024-11-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20241122_1602'),
        ('subscription', '0002_factoritem_affiliate_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.business'),
        ),
    ]
