# Generated by Django 3.2.15 on 2024-11-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_factor_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoritem',
            name='type',
            field=models.CharField(choices=[('af', 'فروش در افیلیت'), ('o', 'سایر')], max_length=2),
        ),
    ]
