# Generated by Django 3.2.15 on 2024-11-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_factoritem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='factoritem',
            name='extension',
        ),
        migrations.DeleteModel(
            name='CompanyExtension',
        ),
        migrations.DeleteModel(
            name='Extension',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
