# Generated by Django 3.2.15 on 2025-07-07 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0005_auto_20241122_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
