# Generated by Django 3.2.15 on 2025-04-21 13:29

import cms.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_button', models.BooleanField(default=False)),
                ('button_title', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('desktop_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('has_default_picture', models.BooleanField(default=False)),
                ('display_seconds', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
                ('link', models.URLField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PopUpElement',
                'ordering': ['-pk'],
                'permissions': (('get.pop_up_element', 'مشاهده عنصر پاپ آپ'), ('create.pop_up_element', 'تعریف عنصر پاپ آپ'), ('update.pop_up_element', 'ویرایش عنصر پاپ آپ'), ('delete.pop_up_element', 'حذف عنصر پاپ آپ'), ('getOwn.pop_up_element', 'مشاهده عنصر پاپ آپ خود'), ('updateOwn.pop_up_element', 'ویرایش عنصر پاپ آپ خود'), ('deleteOwn.pop_up_element', 'حذف عنصر پاپ آپ خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HeaderElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('mobile_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('desktop_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('link', models.URLField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HeaderElement',
                'ordering': ['-pk'],
                'permissions': (('get.header_element', 'مشاهده عنصر هدر'), ('create.header_element', 'تعریف عنصر هدر'), ('update.header_element', 'ویرایش عنصر هدر'), ('delete.header_element', 'حذف عنصر هدر'), ('getOwn.header_element', 'مشاهده عنصر هدر خود'), ('updateOwn.header_element', 'ویرایش عنصر هدر خود'), ('deleteOwn.header_element', 'حذف عنصر هدر خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BannerContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mobile_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('desktop_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('link', models.URLField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pop_up_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.popupelement')),
            ],
            options={
                'verbose_name': 'BannerContentItem',
                'ordering': ['-pk'],
                'permissions': (('get.banner_content_item', 'مشاهده آیتم محتوا بنر'), ('create.banner_content_item', 'تعریف آیتم محتوا بنر'), ('update.banner_content_item', 'ویرایش آیتم محتوا بنر'), ('delete.banner_content_item', 'حذف آیتم محتوا بنر'), ('getOwn.banner_content_item', 'مشاهده آیتم محتوا بنر خود'), ('updateOwn.banner_content_item', 'ویرایش آیتم محتوا بنر خود'), ('deleteOwn.banner_content_item', 'حذف آیتم محتوا بنر خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_scroll_seconds', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(choices=[(1, 'بنر اصلی'), (2, 'بنر دو'), (3, 'بنر سه'), (4, 'بنر چهار'), (5, 'بنر پنج')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BannerContent',
                'ordering': ['-pk'],
                'permissions': (('get.banner_content', 'مشاهده محتوا بنر'), ('create.banner_content', 'تعریف محتوا بنر'), ('update.banner_content', 'ویرایش محتوا بنر'), ('delete.banner_content', 'حذف محتوا بنر'), ('getOwn.banner_content', 'مشاهده محتوا بنر خود'), ('updateOwn.banner_content', 'ویرایش محتوا بنر خود'), ('deleteOwn.banner_content', 'حذف محتوا بنر خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
