# Generated by Django 3.2.15 on 2025-04-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercontentitem',
            name='pop_up_element',
        ),
        migrations.AddField(
            model_name='bannercontentitem',
            name='banner_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.bannercontent'),
        ),
    ]
