# Generated by Django 3.2.15 on 2025-04-25 16:50

import cms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_auto_20250421_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopHomePageStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mobile_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('desktop_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('video', models.FileField(upload_to=cms.models.custom_upload_to)),
                ('link', models.URLField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ShopHomePageStory',
                'ordering': ['-pk'],
                'permissions': (('get.shop_home_page_story', 'مشاهده استوری'), ('create.shop_home_page_story', 'تعریف استوری'), ('update.shop_home_page_story', 'ویرایش استوری'), ('delete.shop_home_page_story', 'حذف استوری'), ('getOwn.shop_home_page_story', 'مشاهده استوری خود'), ('updateOwn.shop_home_page_story', 'ویرایش استوری خود'), ('deleteOwn.shop_home_page_story', 'حذف استوری خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
