# Generated by Django 3.2.15 on 2025-04-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20241122_1721'),
        ('cms', '0003_shophomepagestory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercontentitem',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_content_item', to='subscription.discountcode'),
        ),
        migrations.AddField(
            model_name='headerelement',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_elements', to='subscription.discountcode'),
        ),
        migrations.AddField(
            model_name='popupelement',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_up_elements', to='subscription.discountcode'),
        ),
        migrations.AddField(
            model_name='shophomepagestory',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_home_stories', to='subscription.discountcode'),
        ),
    ]
