# Generated by Django 3.2.15 on 2025-05-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20250426_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='shophomepagestory',
            name='from_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shophomepagestory',
            name='to_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannercontent',
            name='from_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannercontent',
            name='to_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headerelement',
            name='from_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headerelement',
            name='to_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popupelement',
            name='from_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popupelement',
            name='to_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
