# Generated by Django 3.2.15 on 2025-05-18 15:33

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20250502_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shophomepagestory',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shophomepagestory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=cms.models.custom_upload_to),
        ),
    ]
