# Generated by Django 3.2.15 on 2025-05-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20250518_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercontent',
            name='order',
            field=models.IntegerField(choices=[(1, 'بنر اصلی'), (2, 'بنر دو'), (3, 'بنر سه'), (4, 'بنر چهار'), (5, 'بنر پنج'), (6, 'بنر شش')], default=1),
        ),
    ]
