# Generated by Django 3.2.15 on 2025-05-21 14:02

import cms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0069_product_feature_vector'),
        ('cms', '0007_alter_bannercontent_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopHomeHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('from_date_time', models.DateTimeField(blank=True, null=True)),
                ('to_date_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ShopHomeHighlight',
                'ordering': ['-pk'],
                'permissions': (('get.shop_home_highlight', 'مشاهده هایلایت'), ('create.shop_home_highlight', 'تعریف هایلایت'), ('update.shop_home_highlight', 'ویرایش هایلایت'), ('delete.shop_home_highlight', 'حذف هایلایت'), ('getOwn.shop_home_highlight', 'مشاهده هایلایت خود'), ('updateOwn.shop_home_highlight', 'ویرایش هایلایت خود'), ('deleteOwn.shop_home_highlight', 'حذف هایلایت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShopHomeHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('from_date_time', models.DateTimeField(blank=True, null=True)),
                ('to_date_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('desktop_image', models.ImageField(upload_to=cms.models.custom_upload_to)),
                ('type', models.CharField(choices=[('category', 'دسته بندی'), ('brand', 'برند')], max_length=20)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.shophomehighlight')),
            ],
            options={
                'verbose_name': 'ShopHomeHighlightItem',
                'ordering': ['-pk'],
                'permissions': (('get.shop_home_highlight_item', 'مشاهده آیتم هایلایت'), ('create.shop_home_highlight_item', 'تعریف آیتم هایلایت'), ('update.shop_home_highlight_item', 'ویرایش آیتم هایلایت'), ('delete.shop_home_highlight_item', 'حذف آیتم هایلایت'), ('getOwn.shop_home_highlight_item', 'مشاهده آیتم هایلایت خود'), ('updateOwn.shop_home_highlight_item', 'ویرایش آیتم هایلایت خود'), ('deleteOwn.shop_home_highlight_item', 'حذف آیتم هایلایت خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
