# Generated by Django 3.2.15 on 2025-06-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_shophomehighlight_shophomehighlightitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercontentitem',
            name='link',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headerelement',
            name='link',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='popupelement',
            name='link',
            field=models.TextField(max_length=255),
        ),
    ]
