# Generated by Django 3.2.15 on 2025-05-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialauditlog',
            name='action',
            field=models.CharField(choices=[('wallet_top_up_requested', 'Top-up Requested'), ('wallet_top_up_success', 'Top-up Success'), ('wallet_withdraw_wallet_request', 'Wallet Withdrawal Requested'), ('wallet_withdraw_wallet__success', 'Wallet Withdraw Success'), ('wallet_transfer', 'Wallet Transfer'), ('wallet_payment_order', 'Payment for Order'), ('wallet_investment', 'Investment Made'), ('wallet_balance_updated', 'Balance Updated'), ('transaction_failed', 'Transaction Failed'), ('admin_manual_adjustment', 'Manual Adjustment')], max_length=50),
        ),
    ]
