# Generated by Django 3.2.15 on 2025-05-03 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0012_alter_affiliatefactor_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_alter_rate_unique_together'),
        ('main', '0018_business_products'),
        ('financial_management', '0002_alter_financialauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(choices=[('pending', 'بلاتکلیف'), ('success', 'موفق'), ('failed', 'ناموفق')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fso', 'سفارش فروشگاه'), ('fao', 'سفارش های افیلیت'), ('ftw', 'شارژ ولت')], default='fso', max_length=3)),
                ('status', django_fsm.FSMField(choices=[('in', 'شروع شده'), ('pe', 'در حال انجام'), ('su', 'موفق'), ('fa', 'ناموفق'), ('ex', 'منقضی  شده')], default='in', max_length=50, protected=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('gateway', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment', to='main.business')),
                ('shop_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment', to='shop.shoporder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='affiliate.affiliatefactor')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_orders', to='financial_management.payment')),
            ],
            options={
                'unique_together': {('payment', 'order')},
            },
        ),
    ]
