# Generated by Django 3.2.15 on 2025-05-05 13:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0003_auto_20250503_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_fsm.FSMField(choices=[('in', 'شروع شده'), ('pe', 'در حال انجام'), ('su', 'موفق'), ('fa', 'ناموفق'), ('ex', 'منقضی  شده')], default='in', max_length=50),
        ),
    ]
