# Generated by Django 3.2.15 on 2025-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialauditlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_management.payment'),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='action',
            field=models.CharField(choices=[('wallet_top_up_requested', 'Top-up Requested'), ('wallet_top_up_success', 'Top-up Success'), ('wallet_withdraw_wallet_request', 'Wallet Withdrawal Requested'), ('wallet_withdraw_wallet__success', 'Wallet Withdraw Success'), ('wallet_transfer', 'Wallet Transfer'), ('payment_order', 'Payment for Order'), ('wallet_investment', 'Investment Made'), ('wallet_balance_updated', 'Balance Updated'), ('transaction_failed', 'Transaction Failed'), ('payment_failed', 'Payment Failed'), ('admin_manual_adjustment', 'Manual Adjustment')], max_length=50),
        ),
    ]
