# Generated by Django 3.2.15 on 2025-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0005_auto_20250505_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('top-up', 'شارژ ولت'), ('withdraw', 'برداشت'), ('transfer', 'انتقال'), ('investment', 'سرمایه گذاری')], max_length=20),
        ),
    ]
