# Generated by Django 3.2.15 on 2025-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0006_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'بلاتکلیف'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(choices=[('top-up', 'شارژ ولت'), ('withdraw', 'برداشت'), ('payment', 'پرداخت'), ('buy', 'خرید'), ('transfer', 'انتقال'), ('investment', 'سرمایه گذاری')], default='withdraw', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('top-up', 'شارژ ولت'), ('withdraw', 'برداشت'), ('payment', 'پرداخت'), ('buy', 'خرید'), ('transfer', 'انتقال'), ('investment', 'سرمایه گذاری')], max_length=20),
        ),
    ]
