# Generated by Django 3.2.15 on 2025-05-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0007_auto_20250519_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(choices=[('top-up', 'شارژ ولت'), ('withdraw', 'برداشت'), ('payment', 'پرداخت'), ('buy', 'خرید از ولت'), ('transfer', 'انتقال'), ('investment', 'سرمایه گذاری')], default='withdraw', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('top-up', 'شارژ ولت'), ('withdraw', 'برداشت'), ('payment', 'پرداخت'), ('buy', 'خرید از ولت'), ('transfer', 'انتقال'), ('investment', 'سرمایه گذاری')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id__isnull', False)), fields=('reference_id',), name='unique_reference_id'),
        ),
    ]
