# Generated by Django 3.2.15 on 2025-05-19 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_alter_currency_exchange_rate_to_toman'),
        ('financial_management', '0008_auto_20250519_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='used_amount_from_wallet',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exuni_wallet', to='main.business'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exuni_wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
