# Generated by Django 3.2.15 on 2025-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0009_auto_20250519_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField()),
                ('action_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت'), ('free_shipping', 'ارسال رایگان')], max_length=15)),
                ('action_value', models.FloatField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
