# Generated by Django 3.2.15 on 2025-05-20 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_brand_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_management', '0010_discountrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('percentage', 'درصد'), ('fixed_amount', 'مبلغ'), ('free_shipping', 'ارسال رایگان')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='financial_management.discount')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('category', 'دسته بندی'), ('brand', 'برند'), ('product', 'کالا'), ('price_over', 'از قیمت'), ('price_limit', 'تا قیمت'), ('user', 'کاربر')], max_length=20)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='financial_management.discount')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountConditionBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brands', models.ManyToManyField(to='products.Brand')),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_condition', to='financial_management.discountcondition')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountConditionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='products.Category')),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_condition', to='financial_management.discountcondition')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountConditionPriceLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_limit_condition', to='financial_management.discountcondition')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountConditionPriceOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_over', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_over_condition', to='financial_management.discountcondition')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountConditionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_condition', to='financial_management.discountcondition')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountConditionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_condition', to='financial_management.discountcondition')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_management.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discount', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='DiscountRule',
        ),
    ]
