# Generated by Django 3.2.15 on 2025-05-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0011_auto_20250520_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountusage',
            unique_together=set(),
        ),
    ]
