# Generated by Django 3.2.15 on 2025-05-24 15:26

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20250520_1621'),
        ('financial_management', '0012_alter_discountusage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shop_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='shop.shoporder', unique=True),
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='action',
            field=models.CharField(choices=[('wallet_top_up_requested', 'Top-up Requested'), ('wallet_top_up_success', 'Top-up Success'), ('wallet_withdraw_wallet_request', 'Wallet Withdrawal Requested'), ('wallet_withdraw_wallet__success', 'Wallet Withdraw Success'), ('wallet_transfer', 'Wallet Transfer'), ('payment_order', 'Payment for Order'), ('refund_payment_order', 'Refund Payment for Order'), ('wallet_investment', 'Investment Made'), ('wallet_balance_updated', 'Balance Updated'), ('transaction_failed', 'Transaction Failed'), ('payment_failed', 'Payment Failed'), ('admin_manual_adjustment', 'Manual Adjustment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_fsm.FSMField(choices=[('in', 'شروع شده'), ('pe', 'در حال انجام'), ('su', 'موفق'), ('fa', 'ناموفق'), ('ex', 'منقضی  شده'), ('ca', 'لغو شده')], default='in', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(choices=[('top-up', 'شارژ ولت'), ('withdraw', 'برداشت'), ('payment', 'پرداخت'), ('buy', 'خرید از ولت'), ('transfer', 'انتقال'), ('investment', 'سرمایه گذاری'), ('refund', 'برگشت مبلغ سفارش')], default='withdraw', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('top-up', 'شارژ ولت'), ('withdraw', 'برداشت'), ('payment', 'پرداخت'), ('buy', 'خرید از ولت'), ('transfer', 'انتقال'), ('investment', 'سرمایه گذاری'), ('refund', 'برگشت مبلغ سفارش')], max_length=20),
        ),
    ]
