# Generated by Django 3.2.15 on 2025-07-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0013_auto_20250524_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_pan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='zarinpal_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
