# Generated by Django 3.2.15 on 2025-07-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0014_auto_20250701_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
