# Generated by Django 3.2.15 on 2025-07-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0015_auto_20250701_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'بلاتکلیف'), ('success', 'موفق'), ('canceled', 'لغو سفارش'), ('failed', 'ناموفق')], default='pending', max_length=10),
        ),
    ]
