# Generated by Django 3.2.15 on 2025-07-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0017_alter_financialauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialauditlog',
            name='action',
            field=models.CharField(choices=[('wallet_top_up_requested', 'Top-up Requested'), ('wallet_top_up_success', 'Top-up Success'), ('wallet_withdraw_wallet_request', 'Wallet Withdrawal Requested'), ('wallet_withdraw_wallet__success', 'Wallet Withdraw Success'), ('wallet_transfer', 'Wallet Transfer'), ('payment_request', 'request payment for Order'), ('payment_order', 'Payment for Order'), ('payment_for_top_up_wallet', 'Payment for top up wallet'), ('payment_order_from_wallet', 'Payment Order from wallet'), ('refund_payment_order', 'Refund Payment for Order'), ('wallet_investment', 'Investment Made'), ('wallet_balance_updated', 'Balance Updated'), ('transaction_failed', 'Transaction Failed'), ('payment_failed', 'Payment Failed'), ('admin_manual_adjustment', 'Manual Adjustment')], max_length=50),
        ),
    ]
