# Generated by Django 3.2.15 on 2025-07-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0018_alter_financialauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='zarinpal_ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
