# Generated by Django 3.2.15 on 2025-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0019_alter_payment_zarinpal_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
