# Generated by Django 3.2.15 on 2025-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0020_payment_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='callback_called',
            field=models.BooleanField(default=False),
        ),
    ]
