# Generated by Django 3.2.15 on 2025-07-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20250705_1959'),
        ('financial_management', '0021_payment_callback_called'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shop_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='shop.shoporder'),
        ),
    ]
