# Generated by Django 3.2.15 on 2025-08-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_management', '0022_alter_transaction_shop_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
