# Generated by Django 3.2.15 on 2024-08-30 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BUSINESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('domain_address', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('api_token', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_business_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_business_color', models.CharField(blank=True, max_length=7, null=True)),
                ('theme_business_color', models.CharField(blank=True, max_length=7, null=True)),
                ('business_owner_national_card_picture', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('about_us', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(choices=[('om', 'فروشگاه اینترنتی '), ('cs', 'فروشنده پورسانتی'), ('rm', 'فروشگاه نمایندگی')], default='om', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'ordering': ['-pk'],
                'permissions': (('get.business', 'مشاهده کسب و کار'), ('create.business', 'تعریف کسب و کار'), ('update.business', 'ویرایش کسب و کار'), ('delete.business', 'حذف کسب و کار'), ('getOwn.business', 'مشاهده کسب و کار خود'), ('updateOwn.business', 'ویرایش کسب و کار خود'), ('deleteOwn.business', 'حذف کسب و کار خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
