# Generated by Django 3.2.15 on 2024-08-30 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_central',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('exchange_rate_to_rial', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency',
                'ordering': ['-pk'],
                'permissions': (('get.currency', 'مشاهده ارز'), ('create.currency', 'تعریف ارز'), ('update.currency', 'ویرایش ارز'), ('delete.currency', 'حذف ارز'), ('getOwn.currency', 'مشاهده ارز خود'), ('updateOwn.currency', 'ویرایش ارز خود'), ('deleteOwn.currency', 'حذف ارز خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
