# Generated by Django 3.2.15 on 2024-08-30 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20240830_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_sheba_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'ordering': ['-pk'],
                'permissions': (('get.currency', 'مشاهده تامین کننده'), ('create.currency', 'تعریف تامین کننده'), ('update.currency', 'ویرایش تامین کننده'), ('delete.currency', 'حذف تامین کننده'), ('getOwn.currency', 'مشاهده تامین کننده خود'), ('updateOwn.currency', 'ویرایش تامین کننده خود'), ('deleteOwn.currency', 'حذف تامین کننده خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
