# Generated by Django 3.2.15 on 2024-08-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.supplier', 'مشاهده تامین کننده'), ('create.supplier', 'تعریف تامین کننده'), ('update.supplier', 'ویرایش تامین کننده'), ('delete.supplier', 'حذف تامین کننده'), ('getOwn.supplier', 'مشاهده تامین کننده خود'), ('updateOwn.supplier', 'ویرایش تامین کننده خود'), ('deleteOwn.supplier', 'حذف تامین کننده خود')), 'verbose_name': 'Supplier'},
        ),
    ]
