# Generated by Django 3.2.15 on 2024-08-31 22:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='primary_business_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
