# Generated by Django 3.2.15 on 2024-09-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240831_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='manager',
            new_name='storekeeper',
        ),
    ]
