# Generated by Django 3.2.15 on 2024-09-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_manager_store_storekeeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='exchange_rate_to_rial',
            new_name='exchange_rate_to_toman',
        ),
    ]
