# Generated by Django 3.2.15 on 2024-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_exchange_rate_to_rial_currency_exchange_rate_to_toman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate_to_toman',
            field=models.IntegerField(default=1),
        ),
    ]
