# Generated by Django 3.2.15 on 2024-09-06 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_currency_exchange_rate_to_toman'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to=settings.AUTH_USER_MODEL),
        ),
    ]
