# Generated by Django 3.2.15 on 2024-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_business_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
