# Generated by Django 3.2.15 on 2024-09-06 14:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_business_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='primary_business_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='secondary_business_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='theme_business_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
