# Generated by Django 3.2.15 on 2024-11-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240906_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='api_token',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
