# Generated by Django 3.2.15 on 2024-11-22 16:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_business_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_owner_national_card_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=main.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=main.models.custom_upload_to),
        ),
    ]
