# Generated by Django 3.2.15 on 2024-11-24 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20241122_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='customers',
            field=models.ManyToManyField(related_name='businesses_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
