# Generated by Django 3.2.15 on 2024-11-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_product_business'),
        ('main', '0017_business_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='products',
            field=models.ManyToManyField(related_name='businesses', to='products.Product'),
        ),
    ]
