# Generated by Django 3.2.15 on 2025-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_business_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='unique_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
