# Generated by Django 3.2.15 on 2025-05-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_currency_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate_to_toman',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=24),
        ),
    ]
