# Generated by Django 3.2.15 on 2025-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_currency_exchange_rate_to_toman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_central',
        ),
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(choices=[('central', 'انبار مرکزی '), ('packing', 'واحد پردازش سفارشات'), ('other', 'انبار')], default='other', max_length=10),
        ),
    ]
