# Generated by Django 3.2.15 on 2025-07-20 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0021_auto_20250720_1527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0089_rename_store_handle_started_product_packing_handle_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.IntegerField(default=0)),
                ('minimum_inventory', models.IntegerField(default=0)),
                ('aisle', models.CharField(max_length=10, null=True)),
                ('shelf_number', models.CharField(max_length=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_inventory', to='products.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_inventory', to='main.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStoreInventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('i', 'افزایش'), ('d', 'کاهش'), ('s', 'انبارگردانی')], max_length=1)),
                ('quantity', models.IntegerField()),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='store_handle.productstoreinventory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStoreInventoryHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_inventory', models.IntegerField(blank=True, null=True)),
                ('inventory', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_handle', to='products.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_handle', to='main.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackingInventoryHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_inventory', models.IntegerField(blank=True, null=True)),
                ('inventory', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_handle', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHandleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sixteen_digit_code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('postal_weight', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('aisle', models.CharField(max_length=10, null=True)),
                ('shelf_number', models.CharField(max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_handle', to='products.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productstoreinventoryhandle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_applied', False)), fields=('product', 'store'), name='unique_not_applied_product_store_inventory'),
        ),
        migrations.AddIndex(
            model_name='productstoreinventory',
            index=models.Index(fields=['store'], name='store_handl_store_i_d91f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='productstoreinventory',
            index=models.Index(fields=['product'], name='store_handl_product_352c67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productstoreinventory',
            unique_together={('store', 'product')},
        ),
        migrations.AddConstraint(
            model_name='productpackinginventoryhandle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_applied', False)), fields=('product',), name='unique_not_applied_product_packing_inventory'),
        ),
        migrations.AddConstraint(
            model_name='producthandlechange',
            constraint=models.UniqueConstraint(condition=models.Q(('is_applied', False)), fields=('product',), name='unique_not_applied_product_changes'),
        ),
    ]
