# Generated by Django 3.2.15 on 2025-07-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpackinginventoryhandle',
            old_name='min_inventory',
            new_name='minimum_inventory',
        ),
        migrations.RenameField(
            model_name='productstoreinventoryhandle',
            old_name='min_inventory',
            new_name='minimum_inventory',
        ),
    ]
