# Generated by Django 3.2.15 on 2025-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0002_auto_20250720_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthandlechange',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producthandlechange',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producthandlechange',
            name='postal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producthandlechange',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
