# Generated by Django 3.2.15 on 2025-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0003_auto_20250730_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthandlechange',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
