# Generated by Django 3.2.15 on 2025-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0004_producthandlechange_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthandlechange',
            name='expired_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
