# Generated by Django 3.2.15 on 2025-08-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0005_alter_producthandlechange_expired_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=150, null=True)),
                ('max_postal_weight', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('aisle', models.CharField(max_length=10, null=True)),
                ('shelf_number', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
