# Generated by Django 3.2.15 on 2025-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0006_shippingbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingbox',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
