# Generated by Django 3.2.15 on 2025-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0007_shippingbox_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingbox',
            name='foam_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingbox',
            name='postal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
