# Generated by Django 3.2.15 on 2025-08-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0008_auto_20250807_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='store_handle.productstoreinventory')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='store_handle.productstoreinventory')),
            ],
        ),
    ]
