# Generated by Django 3.2.15 on 2025-08-18 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0009_inventorytransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferToPackingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to_packing', to='store_handle.productstoreinventory')),
            ],
        ),
    ]
