# Generated by Django 3.2.15 on 2025-08-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_shoporder_inventory_info'),
        ('store_handle', '0010_transfertopackingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertopackingrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_product_to_packing', to='shop.shoporder'),
        ),
    ]
