# Generated by Django 3.2.15 on 2025-08-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_productinventory_minimum_inventory'),
        ('store_handle', '0011_transfertopackingrequest_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertopackingrequest',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_product_to_packing', to='products.product'),
        ),
        migrations.AlterField(
            model_name='transfertopackingrequest',
            name='from_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_product_to_packing', to='store_handle.productstoreinventory'),
        ),
        migrations.AlterField(
            model_name='transfertopackingrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
