# Generated by Django 3.2.15 on 2025-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0012_auto_20250818_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertopackingrequest',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
