# Generated by Django 3.2.15 on 2025-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0013_transfertopackingrequest_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransfer',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
