# Generated by Django 3.2.15 on 2025-08-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_handle', '0014_inventorytransfer_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoreinventory',
            name='reserved_inventory',
            field=models.IntegerField(default=0),
        ),
    ]
