# Generated by Django 3.2.15 on 2024-08-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('usage', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.option', 'مشاهده تنظیمات'), ('update.option', 'ویرایش تنظیمات')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
