# Generated by Django 3.2.15 on 2025-04-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20250420_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='shop_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.shoporder'),
        ),
    ]
