# Generated by Django 3.2.15 on 2025-04-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment_shop_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtimeofferitems',
            name='limited_time_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.limitedtimeoffer'),
        ),
    ]
