# Generated by Django 3.2.15 on 2025-04-22 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_shoporder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('previous_status', models.CharField(choices=[('pe', 'در انتظار پرداخت'), ('pa', 'پرداخت شده'), ('pr', 'درحال آماده سازی'), ('sh', 'ارسال شده'), ('de', 'تحویل شده'), ('ca', 'لغو شده')], max_length=2)),
                ('new_status', models.CharField(choices=[('pe', 'در انتظار پرداخت'), ('pa', 'پرداخت شده'), ('pr', 'درحال آماده سازی'), ('sh', 'ارسال شده'), ('de', 'تحویل شده'), ('ca', 'لغو شده')], max_length=2)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shop_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shop.shoporder')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
