# Generated by Django 3.2.15 on 2025-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shoporderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedtimeoffer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
