# Generated by Django 3.2.15 on 2025-04-23 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0035_productproperty_value'),
        ('shop', '0009_comment_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('customer', 'product')},
        ),
    ]
