# Generated by Django 3.2.15 on 2025-05-05 13:53

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=django_fsm.FSMField(choices=[('pe', 'در انتظار پرداخت'), ('pa', 'پرداخت شده'), ('pr', 'درحال آماده سازی'), ('sh', 'ارسال شده'), ('de', 'تحویل شده'), ('ca', 'لغو شده')], default='pe', max_length=50),
        ),
    ]
