# Generated by Django 3.2.15 on 2025-05-11 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0063_alter_product_variation_title'),
        ('shop', '0013_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comparison',
            unique_together={('customer', 'product')},
        ),
    ]
