# Generated by Django 3.2.15 on 2025-05-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_comparison_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentaddress',
            name='address_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipmentaddress',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipmentaddress',
            name='house_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
