# Generated by Django 3.2.15 on 2025-05-12 01:14

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20250512_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentaddress',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
