# Generated by Django 3.2.15 on 2025-05-18 20:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_brand_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0019_auto_20250513_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'product')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer'], name='shop_cart_custome_86b221_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['product'], name='shop_cart_product_3d9529_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['customer'], name='shop_compar_custome_6d1dda_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['product'], name='shop_compar_product_c2ffcd_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['customer'], name='shop_wishli_custome_fa9f81_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['product'], name='shop_wishli_product_40cef0_idx'),
        ),
    ]
