# Generated by Django 3.2.15 on 2025-05-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20241122_1721'),
        ('shop', '0020_auto_20250518_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscription.discountcode'),
        ),
    ]
