# Generated by Django 3.2.15 on 2025-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20250519_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipmentaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
