# Generated by Django 3.2.15 on 2025-05-20 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20250520_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipmentaddress',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_zip_code', message='کد پستی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')]),
        ),
    ]
