# Generated by Django 3.2.15 on 2025-05-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20250520_0146'),
    ]

    def create_default_method(apps, schema_editor):
        ShippingMethod = apps.get_model('shop', 'ShippingMethod')
        if not ShippingMethod.objects.all().exists():
            ShippingMethod.objects.create(
                name='ارسال پیش‌فرض',
                price=55000,
                is_active=True,
            )

    operations = [

        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.PositiveIntegerField(default=55000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='shoporder',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shippingmethod'),
        ),

        migrations.RunPython(create_default_method),

    ]
