# Generated by Django 3.2.15 on 2025-05-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20250520_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'default_permissions': (), 'get_latest_by': 'created_at', 'ordering': ['-pk'], 'permissions': ()},
        ),
    ]
