# Generated by Django 3.2.15 on 2025-05-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_management', '0012_alter_discountusage_unique_together'),
        ('shop', '0025_alter_shippingmethod_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='total_discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_management.discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_discounts', to='shop.shoporder')),
            ],
        ),
    ]
