# Generated by Django 3.2.15 on 2025-05-25 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20250520_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_zip_code', message='کد پستی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')]),
        ),
    ]
