# Generated by Django 3.2.15 on 2025-07-05 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0028_auto_20250703_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='print_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prints', to=settings.AUTH_USER_MODEL),
        ),
    ]
