# Generated by Django 3.2.15 on 2025-07-07 13:52

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20250705_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='status',
            field=django_fsm.FSMField(choices=[('pe', 'در انتظار پرداخت'), ('pa', 'جاری'), ('pr', 'درحال بسته بندی'), ('pc', 'بسته بندی شد'), ('sh', 'ارسال شده'), ('de', 'تحویل شده'), ('ca', 'لغو شده'), ('ex', 'منقضی  شده'), ('re', 'مرجوعی')], default='pe', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoporderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pe', 'در انتظار پرداخت'), ('pa', 'جاری'), ('pr', 'درحال بسته بندی'), ('pc', 'بسته بندی شد'), ('sh', 'ارسال شده'), ('de', 'تحویل شده'), ('ca', 'لغو شده'), ('ex', 'منقضی  شده'), ('re', 'مرجوعی')], max_length=2),
        ),
        migrations.AlterField(
            model_name='shoporderstatushistory',
            name='previous_status',
            field=models.CharField(choices=[('pe', 'در انتظار پرداخت'), ('pa', 'جاری'), ('pr', 'درحال بسته بندی'), ('pc', 'بسته بندی شد'), ('sh', 'ارسال شده'), ('de', 'تحویل شده'), ('ca', 'لغو شده'), ('ex', 'منقضی  شده'), ('re', 'مرجوعی')], max_length=2),
        ),
    ]
