# Generated by Django 3.2.15 on 2025-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20250707_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='base_price',
            field=models.PositiveIntegerField(default=68000),
        ),
    ]
