# Generated by Django 3.2.15 on 2025-08-05 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0032_auto_20250724_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='packaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='packager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaged_orders', to=settings.AUTH_USER_MODEL, verbose_name='ادمین بسته\u200cبند'),
        ),
    ]
