# Generated by Django 3.2.15 on 2025-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='inventory_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
