# Generated by Django 3.2.15 on 2025-08-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_shoporder_inventory_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
