# Generated by Django 3.2.15 on 2025-04-24 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0035_productproperty_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProductViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(choices=[('d', 'دسکتاپ'), ('m', 'موبایل'), ('t', 'تبلت'), ('b', 'روبات'), ('o', 'متفرقه')], default='o', max_length=1)),
                ('ip_address', models.CharField(max_length=45)),
                ('referer', models.URLField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shopproductviewlog',
            index=models.Index(fields=['product', 'created_at'], name='crm_shoppro_product_4a6164_idx'),
        ),
        migrations.AddIndex(
            model_name='shopproductviewlog',
            index=models.Index(fields=['user', 'created_at'], name='crm_shoppro_user_id_37698c_idx'),
        ),
    ]
