# Generated by Django 3.2.15 on 2025-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproductviewlog',
            name='browser_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
