# Generated by Django 3.2.15 on 2025-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_shopproductviewlog_browser_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproductviewlog',
            old_name='browser_family',
            new_name='browser_type',
        ),
        migrations.AddField(
            model_name='shopproductviewlog',
            name='browser_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopproductviewlog',
            name='device_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopproductviewlog',
            name='is_touch_device',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopproductviewlog',
            name='os_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopproductviewlog',
            name='os_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
