# Generated by Django 3.2.15 on 2025-04-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_auto_20250425_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproductviewlog',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shopproductviewlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(choices=[('d', 'دسکتاپ'), ('m', 'موبایل'), ('t', 'تبلت'), ('b', 'روبات'), ('o', 'متفرقه')], default='o', max_length=1)),
                ('browser_type', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=100, null=True)),
                ('os_type', models.CharField(blank=True, max_length=100, null=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('device_family', models.CharField(blank=True, max_length=100, null=True)),
                ('is_touch_device', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('query_value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query_value'], name='crm_searchl_query_v_9542e9_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', 'created_at'], name='crm_searchl_user_id_0df00f_idx'),
        ),
    ]
