# Generated by Django 3.2.15 on 2025-04-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20250425_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='search_type',
            field=models.CharField(choices=[('product', 'محصول'), ('category', 'دسته بندی'), ('brand', 'برند'), ('avail', 'فایده'), ('property', 'خصوصیت کالا'), ('raw', 'متن')], default='raw', max_length=8),
        ),
    ]
