# Generated by Django 3.2.15 on 2025-05-01 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0036_productpricehistory_action'),
        ('crm', '0005_searchlog_search_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ss', 'ارسال شده توسط سامانه'), ('sa', 'ارسال شده توسط ادمین')], default='ss', max_length=2)),
                ('send_datetime', models.DateTimeField(blank=True, null=True)),
                ('notification_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_explanation', models.TextField(blank=True, null=True)),
                ('notification_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('sms_text', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_notifications', to='products.product')),
                ('receivers', models.ManyToManyField(related_name='user_in_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_status', models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True)),
                ('sms_status', models.CharField(blank=True, choices=[('p', 'در انتظار ارسال'), ('r', 'خوانده شده'), ('ur', 'خوانده نشده')], max_length=2, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crmUserNotifications', to='crm.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crmNotifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
