# Generated by Django 3.2.15 on 2025-05-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_productpricehistory_action'),
        ('crm', '0006_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='avail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches_log', to='products.avail'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches_log', to='products.category'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches_log', to='products.product'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches_log', to='products.productproperty'),
        ),
        migrations.AddField(
            model_name='shopproductviewlog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='products.category'),
        ),
    ]
