# Generated by Django 3.2.15 on 2025-05-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20250513_1455'),
        ('crm', '0007_auto_20250501_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_btn_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.shoporder'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.shoporderitem'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sort',
            field=models.CharField(choices=[('ac', 'فعالیت ها'), ('or', 'سفارش ها'), ('of', 'تخفیف ها')], default='ss', max_length=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ss', 'ارسال شده توسط سامانه'), ('sa', 'ارسال شده توسط ادمین')], default='ac', max_length=2),
        ),
    ]
