# Generated by Django 3.2.15 on 2025-05-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_brand_options'),
        ('crm', '0008_auto_20250513_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.product'),
        ),
    ]
