# Generated by Django 3.2.15 on 2025-05-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_notification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sort',
            field=models.CharField(choices=[('ac', 'فعالیت ها'), ('or', 'سفارش ها'), ('of', 'تخفیف ها')], default='ac', max_length=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ss', 'ارسال شده توسط سامانه'), ('sa', 'ارسال شده توسط ادمین')], default='ss', max_length=2),
        ),
    ]
