# Generated by Django 3.2.15 on 2025-05-21 13:44

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20250520_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=crm.models.custom_upload_to),
        ),
    ]
