# Generated by Django 3.2.15 on 2025-05-25 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_product_feature_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_inventoryreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreminder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reminders', to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventoryreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
