# Generated by Django 3.2.15 on 2025-08-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20250805_2153'),
        ('products', '0093_auto_20250801_2057'),
        ('crm', '0013_auto_20250525_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='order',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receivers',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.shoporder'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.shoporderitem'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='products.product'),
        ),
    ]
