# Generated by Django 3.2.15 on 2024-08-30 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_supplier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avail',
                'ordering': ['-pk'],
                'permissions': (('get.avail', 'مشاهده فایده'), ('create.avail', 'تعریف فایده'), ('update.avail', 'ویرایش فایده'), ('delete.avail', 'حذف فایده'), ('getOwn.avail', 'مشاهده فایده خود'), ('updateOwn.avail', 'ویرایش فایده خود'), ('deleteOwn.avail', 'حذف فایده خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('is_domestic', models.BooleanField(default=True)),
                ('made_in', models.CharField(blank=True, max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='main.supplier')),
            ],
            options={
                'verbose_name': 'Brand',
                'ordering': ['-pk'],
                'permissions': (('get.brand', 'مشاهده برند'), ('create.brand', 'تعریف برند'), ('update.brand', 'ویرایش برند'), ('delete.brand', 'حذف برند'), ('getOwn.brand', 'مشاهده برند خود'), ('updateOwn.brand', 'ویرایش برند خود'), ('deleteOwn.brand', 'حذف برند خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['-pk'],
                'permissions': (('get.category', 'مشاهده دسته بندی'), ('create.category', 'تعریف دسته بندی'), ('update.category', 'ویرایش دسته بندی'), ('delete.category', 'حذف دسته بندی'), ('getOwn.category', 'مشاهده دسته بندی خود'), ('updateOwn.category', 'ویرایش دسته بندی خود'), ('deleteOwn.category', 'حذف دسته بندی خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('product_id', models.CharField(error_messages={'unique': 'کالا با این شناسه از قبل در اکسونی ثبت شده'}, max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('first_inventory', models.IntegerField(default=0)),
                ('shelf_code', models.IntegerField(blank=True, null=True)),
                ('min_inventory', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('shipping_cost', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('profit_percent', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tax_percent', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('summary_explanation', models.TextField(blank=True, null=True)),
                ('how_to_use', models.TextField(blank=True, null=True)),
                ('product_date', models.DateField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('u', 'در حال بررسی')], default='u', max_length=1)),
                ('postal_weight', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('avails', models.ManyToManyField(blank=True, related_name='products_with_this_avail', to='products.Avail')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.currency')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['-pk'],
                'permissions': (('get.product', 'مشاهده محصول'), ('create.product', 'تعریف محصول'), ('update.product', 'ویرایش محصول'), ('delete.product', 'حذف محصول'), ('getOwn.product', 'مشاهده محصول خود'), ('updateOwn.product', 'ویرایش محصول خود'), ('deleteOwn.product', 'حذف محصول خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductProperty',
                'ordering': ['-pk'],
                'permissions': (('get.product_property', 'مشاهده خصوصیت کالا'), ('create.product_property', 'تعریف خصوصیت کالا'), ('update.product_property', 'ویرایش خصوصیت کالا'), ('delete.product_property', 'حذف خصوصیت کالا'), ('getOwn.product_property', 'مشاهده خصوصیت کالا خود'), ('updateOwn.product_property', 'ویرایش خصوصیت کالا خود'), ('deleteOwn.product_property', 'حذف خصوصیت کالا خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product')),
            ],
            options={
                'verbose_name': 'ProductGallery',
                'ordering': ['-pk'],
                'permissions': (('get.product_gallery', 'مشاهده گالری محصول'), ('create.product_gallery', 'تعریف گالری محصول'), ('update.product_gallery', 'ویرایش گالری محصول'), ('delete.product_gallery', 'حذف گالری محصول'), ('getOwn.product_gallery', 'مشاهده گالری محصول خود'), ('updateOwn.product_gallery', 'ویرایش گالری محصول خود'), ('deleteOwn.product_gallery', 'حذف گالری محصول خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='products_with_this_properties', to='products.ProductProperty'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.supplier'),
        ),
    ]
