# Generated by Django 3.2.15 on 2024-08-31 22:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to),
        ),
    ]
