# Generated by Django 3.2.15 on 2024-09-20 06:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_texture_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to),
        ),
        migrations.AddField(
            model_name='product',
            name='group_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='second_texture_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.custom_upload_to),
        ),
    ]
