# Generated by Django 3.2.15 on 2024-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240920_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
