# Generated by Django 3.2.15 on 2024-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sixteen_digit_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
