# Generated by Django 3.2.15 on 2024-11-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_business_api_token'),
        ('products', '0009_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ManyToManyField(to='main.Business'),
        ),
    ]
