# Generated by Django 3.2.15 on 2024-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_business_api_token'),
        ('products', '0012_alter_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ManyToManyField(related_name='products_for_sale', to='main.Business'),
        ),
    ]
