# Generated by Django 3.2.15 on 2024-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20241122_1602'),
        ('products', '0021_alter_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ManyToManyField(related_name='products_for_sale', to='main.Business'),
        ),
    ]
