# Generated by Django 3.2.15 on 2024-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_business_customers'),
        ('products', '0027_alter_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.ManyToManyField(related_name='products_for_sale', to='main.Business'),
        ),
    ]
