# Generated by Django 3.2.15 on 2024-11-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='business',
        ),
    ]
