# Generated by Django 3.2.15 on 2024-12-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_remove_product_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shelf_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
