# Generated by Django 3.2.15 on 2024-12-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_shelf_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='products.product')),
            ],
        ),
    ]
