# Generated by Django 3.2.15 on 2025-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_productinventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
