# Generated by Django 3.2.15 on 2025-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_productproperty_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='action',
            field=models.CharField(choices=[('i', 'افزایش'), ('d', 'کاهش')], default='i', max_length=1),
        ),
    ]
