# Generated by Django 3.2.15 on 2025-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_productpricehistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventoryhistory',
            name='first_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
