# Generated by Django 3.2.15 on 2025-05-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_productinventoryhistory_first_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='s', max_length=1),
        ),
    ]
