# Generated by Django 3.2.15 on 2025-05-09 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='products.product'),
        ),
    ]
