# Generated by Django 3.2.15 on 2025-05-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_product_variation_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='unique_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
