# Generated by Django 3.2.15 on 2025-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20250509_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='unique_code',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
