# Generated by Django 3.2.15 on 2025-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20250509_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_unique_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
