# Generated by Django 3.2.15 on 2025-05-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_unique_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_code',
            field=models.IntegerField(unique=True),
        ),
    ]
