# Generated by Django 3.2.15 on 2025-05-09 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0049_auto_20250509_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productproperty',
            old_name='value',
            new_name='slug',
        ),
        migrations.CreateModel(
            name='ProductPropertyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='products.productproperty')),
            ],
            options={
                'verbose_name': 'ProductPropertyTerm',
                'ordering': ['-pk'],
                'permissions': (('get.product_property_term', 'مشاهده آیتم خصوصیت کالا'), ('create.product_property_term', 'تعریف آیتم خصوصیت کالا'), ('update.product_property_term', 'ویرایش آیتم خصوصیت کالا'), ('delete.product_property_term', 'حذف آیتم خصوصیت کالا'), ('getOwn.product_property_term', 'مشاهده آیتم خصوصیت کالا خود'), ('updateOwn.product_property_term', 'ویرایش آیتم خصوصیت کالا خود'), ('deleteOwn.product_property_term', 'حذف آیتم خصوصیت کالا خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
