# Generated by Django 3.2.15 on 2025-05-09 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0050_auto_20250509_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
            options={
                'verbose_name': 'ProductAttribute',
                'ordering': ['-pk'],
                'permissions': (('get.product_attribute', 'مشاهده ویژگی کالا'), ('create.product_attribute', 'تعریف ویژگی کالا'), ('update.product_attribute', 'ویرایش ویژگی کالا'), ('delete.product_attribute', 'حذف ویژگی کالا'), ('getOwn.product_attribute', 'مشاهده ویژگی کالا خود'), ('updateOwn.product_attribute', 'ویرایش ویژگی کالا خود'), ('deleteOwn.product_attribute', 'حذف ویژگی کالا خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='productproperty',
            name='unique_code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productpropertyterm',
            name='unique_code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProductAttributeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='products.productattribute')),
                ('terms', models.ManyToManyField(related_name='attribute_in_products', to='products.ProductPropertyTerm')),
            ],
            options={
                'verbose_name': 'ProductAttributeTerm',
                'ordering': ['-pk'],
                'permissions': (('get.product_attribute_term', 'مشاهده آیتم ویژگی کالا'), ('create.product_attribute_term', 'تعریف آیتم ویژگی کالا'), ('update.product_attribute_term', 'ویرایش آیتم ویژگی کالا'), ('delete.product_attribute_term', 'حذف آیتم ویژگی کالا'), ('getOwn.product_attribute_term', 'مشاهده آیتم ویژگی کالا خود'), ('updateOwn.product_attribute_term', 'ویرایش آیتم ویژگی کالا خود'), ('deleteOwn.product_attribute_term', 'حذف آیتم ویژگی کالا خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_attributes', to='products.productproperty'),
        ),
    ]
