# Generated by Django 3.2.15 on 2025-05-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20250509_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='unique_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
