# Generated by Django 3.2.15 on 2025-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_auto_20250509_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('draft', 'پیش\u200cنویس'), ('publish', 'منتشر شده')], default='pending', max_length=7),
        ),
    ]
