# Generated by Django 3.2.15 on 2025-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(error_messages={'unique': 'کالا با این شناسه از قبل در اکسونی ثبت شده'}, max_length=255, unique=True),
        ),
    ]
