# Generated by Django 3.2.15 on 2025-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20250510_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'بدون متغیر'), ('variable', 'دارای متغیر'), ('variation', 'متغیر')], default='simple', max_length=9),
        ),
    ]
