# Generated by Django 3.2.15 on 2025-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
