# Generated by Django 3.2.15 on 2025-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_product_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_type',
            field=models.CharField(choices=[('percent', 'سود درصدی'), ('amount', 'سود مبلغی')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
