# Generated by Django 3.2.15 on 2025-05-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20250510_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profit_percent',
            new_name='profit_margin',
        ),
    ]
