# Generated by Django 3.2.15 on 2025-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_rename_profit_percent_product_profit_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
    ]
