# Generated by Django 3.2.15 on 2025-05-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_product_currency_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first_inventory',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
