# Generated by Django 3.2.15 on 2025-05-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_auto_20250510_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation_title',
            field=models.CharField(default='رنگ', max_length=150),
        ),
    ]
