# Generated by Django 3.2.15 on 2025-05-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_product_variation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variation_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
