# Generated by Django 3.2.15 on 2025-05-11 16:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_alter_product_variation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('unique_code', models.IntegerField(unique=True)),
                ('parent_unique_code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=products.models.custom_upload_to)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.assortment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
