# Generated by Django 3.2.15 on 2025-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_assortment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='assortments',
            field=models.ManyToManyField(related_name='products', to='products.Assortment'),
        ),
    ]
