# Generated by Django 3.2.15 on 2025-05-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_product_assortments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='assortments',
        ),
        migrations.DeleteModel(
            name='Assortment',
        ),
    ]
