# Generated by Django 3.2.15 on 2025-05-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_auto_20250511_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('create.brand', 'تعریف برند'), ('update.brand', 'ویرایش برند'), ('delete.brand', 'حذف برند'), ('updateOwn.brand', 'ویرایش برند خود'), ('deleteOwn.brand', 'حذف برند خود')), 'verbose_name': 'Brand'},
        ),
    ]
