# Generated by Django 3.2.15 on 2025-05-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.brand', 'مشاهده برند'), ('create.brand', 'تعریف برند'), ('update.brand', 'ویرایش برند'), ('delete.brand', 'حذف برند'), ('getOwn.brand', 'مشاهده برند خود'), ('updateOwn.brand', 'ویرایش برند خود'), ('deleteOwn.brand', 'حذف برند خود')), 'verbose_name': 'Brand'},
        ),
    ]
