# Generated by Django 3.2.15 on 2025-05-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
