# Generated by Django 3.2.15 on 2025-06-10 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0069_product_feature_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.avail'),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.feature')),
            ],
            options={
                'verbose_name': 'Avail',
                'ordering': ['-pk'],
                'permissions': (('get.avail', 'مشاهده ویژگی '), ('create.avail', 'تعریف ویژگی '), ('update.avail', 'ویرایش ویژگی '), ('delete.avail', 'حذف ویژگی '), ('getOwn.avail', 'مشاهده ویژگی  خود'), ('updateOwn.avail', 'ویرایش ویژگی  خود'), ('deleteOwn.avail', 'حذف ویژگی  خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
