# Generated by Django 3.2.15 on 2025-06-10 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0070_auto_20250610_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avail',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.avail', 'مشاهده خواص'), ('create.avail', 'تعریف خواص'), ('update.avail', 'ویرایش خواص'), ('delete.avail', 'حذف خواص'), ('getOwn.avail', 'مشاهده خواص خود'), ('updateOwn.avail', 'ویرایش خواص خود'), ('deleteOwn.avail', 'حذف خواص خود')), 'verbose_name_plural': 'خواص محصولات'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.category', 'مشاهده دسته بندی'), ('create.category', 'تعریف دسته بندی'), ('update.category', 'ویرایش دسته بندی'), ('delete.category', 'حذف دسته بندی'), ('getOwn.category', 'مشاهده دسته بندی خود'), ('updateOwn.category', 'ویرایش دسته بندی خود'), ('deleteOwn.category', 'حذف دسته بندی خود')), 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.avail', 'مشاهده ویژگی محصولات '), ('create.avail', 'تعریف ویژگی محصولات '), ('update.avail', 'ویرایش ویژگی محصولات '), ('delete.avail', 'حذف ویژگی محصولات '), ('getOwn.avail', 'مشاهده ویژگی محصولات  خود'), ('updateOwn.avail', 'ویرایش ویژگی محصولات  خود'), ('deleteOwn.avail', 'حذف ویژگی محصولات  خود')), 'verbose_name_plural': 'ویژگی محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.product_attribute', 'مشاهده صفت  کالا'), ('create.product_attribute', 'تعریف صفت  کالا'), ('update.product_attribute', 'ویرایش صفت  کالا'), ('delete.product_attribute', 'حذف صفت  کالا'), ('getOwn.product_attribute', 'مشاهده صفت  کالا خود'), ('updateOwn.product_attribute', 'ویرایش صفت  کالا خود'), ('deleteOwn.product_attribute', 'حذف صفت  کالا خود')), 'verbose_name_plural': 'صفت  کالا'},
        ),
        migrations.AlterModelOptions(
            name='productattributeterm',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.product_attribute_term', 'مشاهده آیتم صفت  کالا'), ('create.product_attribute_term', 'تعریف آیتم صفت  کالا'), ('update.product_attribute_term', 'ویرایش آیتم صفت  کالا'), ('delete.product_attribute_term', 'حذف آیتم صفت  کالا'), ('getOwn.product_attribute_term', 'مشاهده آیتم صفت  کالا خود'), ('updateOwn.product_attribute_term', 'ویرایش آیتم صفت  کالا خود'), ('deleteOwn.product_attribute_term', 'حذف آیتم صفت  کالا خود')), 'verbose_name_plural': 'آیتم صفت  کالا'},
        ),
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.categorization')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی محصولات ',
                'ordering': ['-pk'],
                'permissions': (('get.categorization', 'مشاهده دسته بندی محصولات '), ('create.categorization', 'تعریف دسته بندی محصولات '), ('update.categorization', 'ویرایش دسته بندی محصولات '), ('delete.categorization', 'حذف دسته بندی محصولات '), ('getOwn.categorization', 'مشاهده دسته بندی محصولات  خود'), ('updateOwn.categorization', 'ویرایش دسته بندی محصولات  خود'), ('deleteOwn.categorization', 'حذف دسته بندی محصولات  خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
