# Generated by Django 3.2.15 on 2025-06-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_auto_20250610_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.brand', 'مشاهده برند'), ('create.brand', 'تعریف برند'), ('update.brand', 'ویرایش برند'), ('delete.brand', 'حذف برند'), ('getOwn.brand', 'مشاهده برند خود'), ('updateOwn.brand', 'ویرایش برند خود'), ('deleteOwn.brand', 'حذف برند خود')), 'verbose_name_plural': 'برند'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.product', 'مشاهده محصول'), ('create.product', 'تعریف محصول'), ('update.product', 'ویرایش محصول'), ('delete.product', 'حذف محصول'), ('getOwn.product', 'مشاهده محصول خود'), ('updateOwn.product', 'ویرایش محصول خود'), ('deleteOwn.product', 'حذف محصول خود')), 'verbose_name_plural': 'محصول'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.product_gallery', 'مشاهده گالری محصول'), ('create.product_gallery', 'تعریف گالری محصول'), ('update.product_gallery', 'ویرایش گالری محصول'), ('delete.product_gallery', 'حذف گالری محصول'), ('getOwn.product_gallery', 'مشاهده گالری محصول خود'), ('updateOwn.product_gallery', 'ویرایش گالری محصول خود'), ('deleteOwn.product_gallery', 'حذف گالری محصول خود')), 'verbose_name_plural': 'گالری محصول'},
        ),
        migrations.AlterModelOptions(
            name='productproperty',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.product_property', 'مشاهده خصوصیت کالا'), ('create.product_property', 'تعریف خصوصیت کالا'), ('update.product_property', 'ویرایش خصوصیت کالا'), ('delete.product_property', 'حذف خصوصیت کالا'), ('getOwn.product_property', 'مشاهده خصوصیت کالا خود'), ('updateOwn.product_property', 'ویرایش خصوصیت کالا خود'), ('deleteOwn.product_property', 'حذف خصوصیت کالا خود')), 'verbose_name_plural': 'خصوصیت کالا'},
        ),
        migrations.AlterModelOptions(
            name='productpropertyterm',
            options={'default_permissions': (), 'get_latest_by': 'pk', 'ordering': ['-pk'], 'permissions': (('get.product_property_term', 'مشاهده آیتم خصوصیت کالا'), ('create.product_property_term', 'تعریف آیتم خصوصیت کالا'), ('update.product_property_term', 'ویرایش آیتم خصوصیت کالا'), ('delete.product_property_term', 'حذف آیتم خصوصیت کالا'), ('getOwn.product_property_term', 'مشاهده آیتم خصوصیت کالا خود'), ('updateOwn.product_property_term', 'ویرایش آیتم خصوصیت کالا خود'), ('deleteOwn.product_property_term', 'حذف آیتم خصوصیت کالا خود')), 'verbose_name_plural': 'آیتم خصوصیت کالا'},
        ),
    ]
