# Generated by Django 3.2.15 on 2025-06-12 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0072_auto_20250610_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_auto_created', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('explanation', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.productbenefit', verbose_name='والد')),
            ],
            options={
                'ordering': ['-pk'],
                'permissions': (('get.product_benefit', 'مشاهده خاصیت '), ('create.product_benefit', 'تعریف خاصیت '), ('update.product_benefit', 'ویرایش خاصیت '), ('delete.product_benefit', 'حذف خاصیت '), ('getOwn.product_benefit', 'مشاهده خاصیت  خود'), ('updateOwn.product_benefit', 'ویرایش خاصیت  خود'), ('deleteOwn.product_benefit', 'حذف خاصیت  خود')),
                'get_latest_by': 'pk',
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
