# Generated by Django 3.2.15 on 2025-06-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_productbenefit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductBenefit',
        ),
    ]
