# Generated by Django 3.2.15 on 2025-06-12 23:24

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_delete_productbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=products.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='avail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.avail'),
        ),
    ]
