# Generated by Django 3.2.15 on 2025-06-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0075_auto_20250612_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avail',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.avail'),
        ),
    ]
