# Generated by Django 3.2.15 on 2025-06-13 02:08

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_alter_avail_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=products.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='feature',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.feature'),
        ),
    ]
