# Generated by Django 3.2.15 on 2025-06-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
        ),
    ]
