# Generated by Django 3.2.15 on 2025-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_alter_product_variation_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sixteen_digit_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
