# Generated by Django 3.2.15 on 2025-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_alter_product_sixteen_digit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avail',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avail',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorization',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feature',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
