# Generated by Django 3.2.15 on 2025-07-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0083_auto_20250715_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_margin',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('percent', ' درصدی'), ('amount', ' مبلغی')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_type',
            field=models.CharField(choices=[('percent', ' درصدی'), ('amount', ' مبلغی')], default='percent', max_length=10),
        ),
    ]
