# Generated by Django 3.2.15 on 2025-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0084_auto_20250715_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_margin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
