# Generated by Django 3.2.15 on 2025-07-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_auto_20250716_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pr', 'بررسی'), ('pending', 'در انتظار'), ('draft', 'پیش\u200cنویس'), ('publish', 'منتشر شده')], default='pending', max_length=7),
        ),
    ]
