# Generated by Django 3.2.15 on 2025-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_auto_20250718_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aisle',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store_handle_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='store_handle_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='postal_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinventoryhistory',
            name='action',
            field=models.CharField(choices=[('i', 'افزایش'), ('d', 'کاهش'), ('s', 'انبار گردانی')], max_length=1),
        ),
    ]
