# Generated by Django 3.2.15 on 2025-07-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0088_auto_20250720_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='store_handle_started',
            new_name='packing_handle_done',
        ),
    ]
