# Generated by Django 3.2.15 on 2025-08-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0090_auto_20250730_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_currency_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
