# Generated by Django 3.2.15 on 2025-08-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0091_auto_20250801_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product'),
        ),
    ]
