# Generated by Django 3.2.15 on 2025-08-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_alter_productpricehistory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expired_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
