# Generated by Django 3.2.15 on 2025-08-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0093_auto_20250801_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='total_inventory',
            field=models.IntegerField(default=0),
        ),
    ]
