# Generated by Django 3.2.15 on 2025-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_productinventory_total_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='minimum_inventory',
            field=models.IntegerField(default=0),
        ),
    ]
