# Generated by Django 3.2.15 on 2025-08-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0095_productinventory_minimum_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aisle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
